# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TableEdit"
charset: "UTF-8"
session: YAML
session_expires: 8 hours
table_editor_plugins: [ "Event", "Locator" ]
#base_url: "admin/"

# Template engine for front page
template: "template_toolkit"

# include timestamp in log format
logger_format: "%t [%P] %L @%D> %m in %f l. %l"



plugins:
# Sample configuration for authentication with Dancer::Plugin::Auth::Extensible
  Auth::Extensible:
    disable_roles: 0
    no_login_handler: 1
    login_page: /login
    logout_page: /logout
    denied_page: /login/denied
    no_default_pages: 1
    no_api_change_warning: 1
    realms:
      users:
        provider: 'DBIC'
        db_connection_name: 'default'
        users_resultset: User
        roles_relationship: roles
        role_column: name
        username_column: username
        password_column: password
        password_check: check_password
