# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TableEdit"
charset: "UTF-8"
session: YAML
session_expires: 8 hours

# include timestamp in log format
logger_format: "%t [%P] %L @%D> %m in %f l. %l"

plugins:

# TableEdit will pick default databse
 
#   DBIC:         
#    default:
#      dsn: dbi:mysql:dbname=bizi
#      schema_class: TableEdit::Schema
#      user: __USERNAME__
#      pass: __PASSWORD__
#      options:
#        mysql_enable_utf8: 1
#     default:
#        dsn: dbi:Pg:dbname=__DATABASE_NAME__;host=localhost;port=__PORT__
#        schema_class: TableEdit::Schema
#        user: __USERNAME__
#        pass: __PASSWORD__
#        options:

# Sample configuration for authentication with Dancer::Plugin::Auth::Extensible

  Auth::Extensible:
    disable_roles: 0
    no_login_handler: 1
    login_page: /login
    logout_page: /logout
    denied_page: /login/denied
    no_default_pages: 1
    no_api_change_warning: 1
    realms:
      users:
        provider: 'DBIC'
        db_connection_name: 'default'
        users_resultset: User
        roles_relationship: roles
        role_column: name
        username_column: username
        password_column: password
        password_check: check_password
