# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TableEdit"
charset: "UTF-8"
session: YAML
session_expires: 8 hours

plugins:

# TableEdit will pick default databse
 
#   DBIC:         
#    default:
#      dsn: dbi:mysql:dbname=bizi
#      schema_class: TableEdit::Schema
#      user: __USERNAME__
#      pass: __PASSWORD__
#      options:
#        mysql_enable_utf8: 1
#     default:
#        dsn: dbi:Pg:dbname=__DATABASE_NAME__;host=localhost;port=__PORT__
#        schema_class: TableEdit::Schema
#        user: __USERNAME__
#        pass: __PASSWORD__
#        options:
